USE db_projek_surat;

INSERT INTO letter_codes (name, code, type, created_at, updated_at) VALUES
-- Menambahkan data jenis surat
('Surat Keputusan', 'SK', 'jenis_surat', NOW(), NOW()),
('Peraturan', 'P', 'jenis_surat', NOW(), NOW()),
('Nota Kesepahaman', 'MOU', 'jenis_surat', NOW(), NOW()),
('Surat Perjanjian', 'MOA', 'jenis_surat', NOW(), NOW()),
('Rencana Implementasi Kerjasama', 'IA', 'jenis_surat', NOW(), NOW()),
('Surat Keterangan/Pernyataan', 'SKP', 'jenis_surat', NOW(), NOW()),
('Surat Tugas', 'ST', 'jenis_surat', NOW(), NOW()),
('Surat Perintah Perjalanan Dinas', 'SPPD', 'jenis_surat', NOW(), NOW()),
('Surat Kuasa', 'S.KUASA', 'jenis_surat', NOW(), NOW()),
('Surat Edaran', 'SE', 'jenis_surat', NOW(), NOW()),
('Memo Internal', 'MI', 'jenis_surat', NOW(), NOW()),
('Berita Acara', 'BA', 'jenis_surat', NOW(), NOW()),
('Surat Rekomendasi', 'SRM', 'jenis_surat', NOW(), NOW()),
('Surat Pengantar', 'SP', 'jenis_surat', NOW(), NOW()),
('Surat Perintah', 'SPT', 'jenis_surat', NOW(), NOW()),
('Surat Undangan', 'UNd', 'jenis_surat', NOW(), NOW()),
('Sertifikat', 'SERT', 'jenis_surat', NOW(), NOW()),
('Nota Dinas', 'ND', 'jenis_surat', NOW(), NOW()),

-- Penambahan data Jabatan
('Senat', 'A', 'jabatan', NOW(), NOW()),
('Dewan Pertimbangan/Pengawas', 'B', 'jabatan', NOW(), NOW()),
('Rektor', 'RK', 'jabatan', NOW(), NOW()),
('Wakil Rektor I', 'WR.I', 'jabatan', NOW(), NOW()),
('Wakil Rektor II', 'WR.II', 'jabatan', NOW(), NOW()),
('Fakultas Ilmu Kesehatan', 'FIK', 'jabatan', NOW(), NOW()),
('Fakultas Sains dan Teknologi', 'FST', 'jabatan', NOW(), NOW()),
('Fakultas Ekonomi dan Bisnis', 'FEB', 'jabatan', NOW(), NOW()),
('LPPM', 'LPPM', 'jabatan', NOW(), NOW()),
('LP3M', 'LP3M', 'jabatan', NOW(), NOW()),
('LPTIK', 'LPTIK', 'jabatan', NOW(), NOW()),
('UPT Perpustakaan', 'LIB', 'jabatan', NOW(), NOW()),
('Biro Keuangan', 'KEU', 'jabatan', NOW(), NOW()),
('Biro Kepegawaian', 'SDM', 'jabatan', NOW(), NOW()),
('Biro Administrasi Akademik', 'BAA', 'jabatan', NOW(), NOW()),
('Biro Administrasi Umum', 'BAU', 'jabatan', NOW(), NOW()),
('Biro Sarana & Prasarana', 'BSP', 'jabatan', NOW(), NOW()),
('Revenue Genereration Unit', 'RGU', 'jabatan', NOW(), NOW()),
('Kemahasiswaan & Prestasi', 'KMH', 'jabatan', NOW(), NOW()),
('Alumni & Kerjasama', 'AKS', 'jabatan', NOW(), NOW()),
('Hubungan Masyarakat & Marketing', 'HMR', 'jabatan', NOW(), NOW()),
('Program Studi D3 Teknologi Laboratorium Medis', 'KP.A', 'jabatan', NOW(), NOW()),
('Program Studi S1 Farmasi', 'KP.B', 'jabatan', NOW(), NOW()),
('Program Studi D3 Farmasi', 'KP.C', 'jabatan', NOW(), NOW()),
('Program Studi S1 Administrasi Kesehatan', 'KP.D', 'jabatan', NOW(), NOW()),
('Program Studi S1 Fisioterapi', 'KP.E', 'jabatan', NOW(), NOW()),
('Program Studi S1 Bisnis Digital', 'KP.F', 'jabatan', NOW(), NOW()),
('Program Studi S1 Kewirasahaan', 'KP.G', 'jabatan', NOW(), NOW()),
('Program Studi S1 Rekayasa Perangkat Lunak', 'KP.H', 'jabatan', NOW(), NOW()),
('Program Studi S1 Sistem Informasi', 'KP.I', 'jabatan', NOW(), NOW()),
('Program Studi Pendidikan Profesi Apoteker', 'KP.J', 'jabatan', NOW(), NOW()),
('Laboratorium Pendidikan', 'LAB', 'jabatan', NOW(), NOW());
